name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  security-events: write
  actions: read
  contents: read


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execução do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    uses: Devops-Pro-Organization/devops-pro-desafio-cicd-01/.github/workflows/testes.yml@main
    secrets: inherit

  release:
    name: Criação de Release
    runs-on: ubuntu-latest
    needs: [testes]
    steps: 
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Analise do Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile

      - name: Efetuando o Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src
          file: src/Review-Filmes.Web/Dockerfile
          tags: |
            diogofiaminghi/projeto-devops-pro-filmes:latest
            diogofiaminghi/projeto-devops-pro-filmes:v${{ github.run_number }}
      
      - name: Executar o Trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "image"
          image-ref: diogofiaminghi/projeto-devops-pro-filmes:v${{ github.run_number }}
          format: sarif
          output: trivy-docker-result.sarif
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

      - name: Upload do resultado do Trivy para o GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: trivy
          sarif_file: trivy-docker-result.sarif
          
  deploy-homolog:
    needs: [release]
    uses: Devops-Pro-Organization/devops-pro-desafio-cicd-01/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment-name: homologacao
      environment-url: http://homologacao.diogofiaminghi.com.br/

  teste-end-to-end:
    name: Teste End to End
    runs-on: ubuntu-latest
    needs: [deploy-homolog]
    environment:
      name: homologacao
    container:
      image: fabricioveronez/webdriver-dotnet:chrome
      env:
        BASE_URL: "http://${{ vars.BASE_URL }}"
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Execução do Teste End to End
        working-directory: ./src
        run: dotnet test ./Review-Filmes.Test.EndToEnd/Review-Filmes.Test.EndToEnd.csproj

  deploy-producao:
    needs: [teste-end-to-end]
    uses: Devops-Pro-Organization/devops-pro-desafio-cicd-01/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      environment-name: producao
      environment-url: http://producao.diogofiaminghi.com.br/