name: Execução de Testes

on:
  workflow_call:

jobs:
  unit-test:
    name: Teste de Unidade
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execução do Teste de Unidade
        working-directory: ./src
        run: dotnet test Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj
  
  integration-test:
    name: Teste de Integração
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: review
          POSTGRES_PASSWORD: postgrespwd
          POSTGRES_DB: review-filmes
        ports:
          - 5432:5432
        #options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Execução do Teste de Integração
        working-directory: ./src
        run: dotnet test Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=review-filmes;Username=review;Password=postgrespwd"

  sonarqube:
    name: Scan com o Sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"

      - name: Obtendo o código do projeto
        uses: actions/checkout@v4 

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Restaurar Dependências
        run: dotnet restore
  
      - name: Compilar o Projeto
        run: dotnet build --no-restore
  
      - name: Executar Testes com Cobertura
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory coverage
  
      - name: Converter Cobertura para Formato SonarQube
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator -reports:coverage/**/coverage.cobertura.xml -targetdir:coverage/reports -reporttypes:SonarQube
  
      - name: Executar Análise no SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          dotnet sonarscanner begin /k:"devops-pro-desafio-cicd-01" /o:"Devops-Pro-Organization" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.opencover.reportsPaths=coverage/reports/SonarQube.xml
          dotnet build --no-restore
          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

      
